### ISSUE TITLE
Square Brackets beside Project Name using Harvest Integration from 42nd

### ISSUE THREAD

**Issue by KoltonG** [42ndCo/Harvest-Time-Tracking#1]
Hi!
 
I just installed the Harvest integration from 42nd, and for some reason, all the project names in the integration interface are showing two square brackets to their left? I am not sure if this is a bug or not, but some clarification would be great!

Here is a screenshot.
![harvest integration by 42nd - square bracket issue](https://user-images.githubusercontent.com/3606121/33947651-54a587e6-dffb-11e7-8ca3-905750b3e423.png)

Associated JIRA Question: [https://community.atlassian.com/t5/Marketplace-Apps-questions/Square-Brackets-beside-Project-Name-using-Harvest-Integration/qaq-p/688554#M38483](https://community.atlassian.com/t5/Marketplace-Apps-questions/Square-Brackets-beside-Project-Name-using-Harvest-Integration/qaq-p/688554#M38483)

**Comment by MartinPeverelli** [comment]
Resolved a long long time ago via JIRA Question.
