### ISSUE TITLE
Integration is not responding

### ISSUE THREAD

**Issue by Philipdl** [42ndCo/Harvest-Time-Tracking#2]
Hi. We just installed the plugin last week, and was actually very happy the functionality. But yesterday the Harvest integration doesn't respond.
Any idea how to solve it?

![skaermbillede 2018-01-30 kl 08 31 47](https://user-images.githubusercontent.com/35951503/35553407-14ee3a68-0598-11e8-830c-7ab5b0d16f6e.png)

**Comment by Philipdl** [comment]
![skaermbillede 2018-01-30 kl 08 34 05](https://user-images.githubusercontent.com/35951503/35553485-62f77b2a-0598-11e8-9ae4-8827c36f8fa8.png)

**Comment by MartinPeverelli** [comment]
Hi @Philipdl 
I see no connectivity issues directly on our servers. Everything is up and running.
What you are experiencing, seems to be a failure to reach our servers.
Could you try to directly load our site? https://jira-harvest.42nd.co
What you should see, is a message stating that "your license is expired".
If you see that message, then you are able to reach the server without a problem, so I would suggest clearing up the cache on your browser (which browser is that, by the way?)

If you can't see that message, and see a broken page much like your screenshot, then I would think that there is some firewall blocking you. Maybe someone form IT blocked our domain, or restricted access somehow. I would check that, and make sure there is no network firewall blocking access to the plugin. Again, if that is resolved, please clear your browsers' cache and try again.

Please let us know if that resolves or advances the issue in any way.

Thanks!

**Comment by Philipdl** [comment]
Hi again
Thanks for the support. We have solved the issue now.
I have updated my review :)

-- 
Med venlig hilsen/Kind regards

Philip Danhøj Larsen
Project Manager

appstract
Rued Langgaards Vej 8
2300 København S


Mobil: +45 3175 5794
Mail: pdl@appstract.dk
