### ISSUE TITLE
Search needs improvement

### ISSUE THREAD

**Issue by johnvincentlovell** [42ndCo/Harvest-Time-Tracking#3]
Really awesome plugin. I switched our team to your version over the official one specifically because of the way this plugin writes to Jira's Time Tracking fields. 

However, I have to say that I miss being able to search for projects by typing in the name of clients they belong to. As it stands, it seems like you can only search for projects - which is useful, no doubt. However, I know I'm going to get push back from my co-workers who aren't able to search for projects by typing in the name of the client they're associated with. 

Any chance this would be considered on an upcoming release? 

Thanks!

**Comment by MartinPeverelli** [comment]
Thanks! Yes, we have an upcoming release with small UX improvements such as better search/filters ( search by client, internationalization support, faster loading), submit timer by hitting enter and some other minor tweaks. 
I can’t give you a deadline, but it will be soonish.

**Comment by johnvincentlovell** [comment]
Ah that's great to hear! Thanks for your response. Looking forward to the upcoming release.

**Comment by MartinPeverelli** [comment]
Hi @johnvincentlovell 
I just wanted to reach out since we deployed a new version of the plugin today, that covers all the things discussed in this issue. The update should propagate automagically or by a browser cache refresh.

Thanks!

**Comment by johnvincentlovell** [comment]
yes, that's awesome! I noticed that while working today. great job. 👍 😄
